const { spawnSync } = require('child_process')
const { existsSync, writeFileSync } = require('fs')

const SESSION_ID = 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoieUFxbjQ4NnR6dGdKWXNqcXpvMDlmbXB3UXBDNTNGbk9lWmRDeFlPeDAzdz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoidldtUkExZU1CNkhNQWxNanZEMmFOcnBNT2lUWmJIR1RreVBJZEVHcVdSYz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJNRTN6OHZGVWZTOEJ4bEN6V0kxQ0puTDB5OTlWT2N4UGYxaHpJcFcybGtZPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ6MnFDR0JxZVduZHVLS2JEdnA2TUZtK2g4Q09NM1VwdkROZW13Tit6YldRPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImNHTUNqQm54TGJUemFxNnJoVnF1YzB5Q2UyVTNLeXBpNXIwSnBaa2RESDQ9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImZZRU5zaHhOdDlsTXNkNEFMV1lXYVdGRmVqWHdmVWFYUDZnR2NMd0twRlE9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQURLMHA0bXZldERaWVNjeU85UForR3gzY1FnQXNINGtscXVyM0xjSWhYTT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiY3JzczBWUTU3RHo0bFdtbmxGZzdzWkQxSG1hYk1HTFdCeVJpcWFseUQyUT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik91ckpDUDd5bCt3eUdhSTdnV2Y3OStaV1FkWVdUSWZlbVZOc2Q4UW1kbjB4MTQ0Qy9VWkw2eUlyWGFtN2xzcWpKTldKVmNaQ0R0WmllK29kalFoMENBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjQzLCJhZHZTZWNyZXRLZXkiOiJzOUZDREJHRlZZYTdsSUFObkpsbkZpTnd4QzZEdEtGL3UyejU3SWtXMThZPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJ5WDdrQXR1ZlRsU3R1Mi1mRzF6eEdnIiwicGhvbmVJZCI6IjMxYjUyNTNmLTcwOGItNGU5MC1hZDJlLWIxY2U5ODA2MmYxZCIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJveGFZSUVlK2lOV3dpQWtubzZ2am5rbGJLU0k9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoidFFpdzdLbDZ1Y0RSeHNYMitVLzVha0MwMkJNPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IkJKTTJXR1dZIiwibWUiOnsiaWQiOiIyMjE3NzgyNzEzMTU6NjRAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoi8J2Qi/CdkI7wnZCR8J2QgyDwnZG+8J2RtvCdkbPwnZGtIPCdkbMu8J2Rs/CdkbbwnZKA8J2RqyDwnZGo8J2RtfCdkbbwnZG18J2SgPCdkbTwnZG28J2RvPCdkbog8J2Rs/CdkajwnZG18J2Rq/CdkazwnZG5In0sImFjY291bnQiOnsiZGV0YWlscyI6IkNKQytsYW9ERU1ucTJic0dHQW9nQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJwbFVRVFZBbklZaFpMRlNjYitTWithUzdlYjlRUUptMGs0Y0IrTCtLdVJJPSIsImFjY291bnRTaWduYXR1cmUiOiJZcDlJbWhHNXl6cEFvdG44OVpOZm9id2FqVWFkYWZvWHpIVUY1bGd2N240VnExaEI0b3lMa0JJa0R1dUhxUFNRVWxJNU55MkgwQ3kvaXIxSTVBcjZEZz09IiwiZGV2aWNlU2lnbmF0dXJlIjoibk9UbVhkMldHK2Z3ck92K0FqRzdFbG4wU1ZsWEs3OHc5dS9FUVlHUCtHSzhVTTU1V2Z5UXB1WCtkc1YvY2lSZnViQmlwYW5zdm9ONVoyYXpLZUdoQ0E9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyMjE3NzgyNzEzMTU6NjRAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCYVpWRUUxUUp5R0lXU3hVbkcva21mbWt1M20vVUVDWnRKT0hBZmkvaXJrUyJ9fV0sInBsYXRmb3JtIjoic21iYSIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTczNTgxNjUzNCwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFGZlAifQ==' // Edit this line only, don't remove ' <- this symbol

if (!existsSync('Itxxwasi')) {
  console.log('Cloning the repository...')
  const cloneResult = spawnSync(
    'git',
    ['clone', 'https://github.com/Itxxwasi/WASI-MD-V.git', 'Itxxwasi'],
    {
      stdio: 'inherit',
    }
  )

  if (cloneResult.error) {
    throw new Error(`Failed to clone the repository: ${cloneResult.error.message}`)
  }

  const configPath = 'Itxxwasi/config.env'
  try {
    console.log('Writing to config.env...')
    writeFileSync(configPath, `VPS=true\nSESSION_ID=${SESSION_ID}`)
  } catch (err) {
    throw new Error(`Failed to write to config.env: ${err.message}`)
  }

  console.log('Installing dependencies...')
  const installResult = spawnSync('yarn', ['install', '--network-concurrency', '3'], {
    cwd: 'Itxxwasi',
    stdio: 'inherit',
  })

  if (installResult.error) {
    throw new Error(`Failed to install dependencies: ${installResult.error.message}`)
  }
}

spawnSync('yarn', ['start'], { cwd: 'Itxxwasi', stdio: 'inherit' })
